#!/bin/bash

export REPO_DIR="$HOME/linux-dev-env"

# Journey
# The journey of a thousand miles begins with one step:
# 1. System bringup: Installation on the machine
# 1.1 System Env:
#     UEFI: Disable CMS feautre. (UEFI && GPT only)
#     Archlinux: Network setup please google it first.
#
#     reboot and login archlinuxiso system.

#1.
NETDEV=enp0s3
if [ ! -n "$NETDEV" ]; then
  echo "NETDEV IS NULL."
else
  echo "Let's start!"
fi

#Config system
cd
grep -A 1 China /etc/pacman.d/mirrorlist > tmp
sed -i 's/--//g' tmp
cp tmp /etc/pacman.d/mirrorlist

echo "[archlinuxfr]" >> /etc/pacman.conf
echo "SigLevel = Never" >> /etc/pacman.conf
echo "Server = http://repo.archlinux.fr/\$arch" >> /etc/pacman.conf
echo "Done: mirrorlist"

#2.
rm /etc/localtime
ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
hwclock --systohc --utc
echo "Done: Time sync"

#3.
echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
locale-gen

echo LANG=en_US.UTF-8 > /etc/locale.conf
export LANG=en_US.UTF-8
echo "Done: locale"

#4.
HOSTNAME=arch
echo $HOSTNAME > /etc/hostname

echo "127.0.0.1		localhost" > /etc/hosts
echo "::1		localhost" >> /etc/hosts
echo "127.0.1.1		$HOSTNAME.localdomain	$HOSTNAME" >> /etc/hosts

systemctl enable dhcpcd@$NETDEV.service
echo "Done: Network"

#5.
echo "Sync mirror..."
pacman -Sy
echo "Done: sync"

#6.
pacman -S linux-headers
echo "Done: install headers"

#7.
#if EFI
#*EFI*:
#pacman -S efibootmgr grub-efi-x86_64
#grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=arch_grub --recheck --debug
#Tested, It had no effect on me. Please ignore step: 24
#cp /usr/share/locale/en\@quot/LC_MESSAGES/grub.mo /boot/grub/locale/en.mo (Not sure about this, need to check)
#else
#*NON EF*: GeneralBios:
pacman -S grub
grub-install --target=i386-pc /dev/sda
#endif

grub-mkconfig -o /boot/grub/grub.cfg
echo "Done: install grub"

#8.
echo "Changing root password..."
passwd #Change root pswd

#9.
echo "Add user wds password..."
useradd -m -g users -G wheel,storage,power -s /bin/bash wds
passwd wds

#10.
echo "wds ALL=(ALL) ALL" >> /etc/sudoers

#fonts
pacman -S xorg-fonts-{100dpi,75dpi,cyrillic,misc,type1}
pacman -S noto-fonts-cjk
cp -a $REPO_DIR/fonts/custom /usr/share/fonts/
fc-cache -fv
fc-list | grep Hermit
fc-list | grep Source

#APPs install
pacman -S rxvt-unicode openssh vim virtualbox-guest-utils virtualbox-guest-modules-arch
pacman -S xorg-{server,xinit,apps}
pacman -S arandr zsh
systemctl enable sshd.service
systemctl start sshd.service

pacman -S yaourt
yaourt peco
yaourt google-chrome

#StumpWM
pacman -S sbcl
curl -O https://beta.quicklisp.org/quicklisp.lisp
sbcl --load quicklisp.lisp
#(quicklisp-quickstart:install)
#(ql:add-to-init-file)
#(ql:quickload "clx")
#(ql:quickload "cl-ppcre")
#(ql:quickload "alexandria")

git clone git://github.com/stumpwm/stumpwm.git
cd stumpwm
autoconf && ./configure && make
sudo make install
cd

#11. Copy config
cd $REPO_DIR
cp -a .dotfiles /home/wds/
chown -R wds /home/wds/.dotfiles/
cp usr-setup /home/wds/
chown wds /home/wds/usr-setup
#Do not install Hermit from AUR, this will cause stumpwm hangup.
exit
